### ISSUE TITLE
Standalone app logs "Installed ..." on exec

### ISSUE THREAD

**Issue by etpinard** [plotly/image-exporter#77]
Making an issue out of @n-riesco's https://github.com/plotly/image-exporter/pull/66#issuecomment-381108301:

I've noticed that running the AppImage version now prints out the message:
```
installed: X-AppImage-BuildId=5a6b0d10-3f0d-11a8-3934-f7a37a902d22 image: X-AppImage-BuildId=5a6b0d10-3f0d-11a8-3934-f7a37a902d22
```
I don't remember this happening before.

**Comment by JamesCropcho** [comment]
I would presume it is not bad, that this message is being printed?

Or, is this issue opened with the implied goal to suppress this message?

**Comment by etpinard** [comment]
I think it's pretty bad. Not critical, but pretty bad. That thing isn't useful for anyone.

**Comment by JamesCropcho** [comment]
I want to bring https://github.com/electron-userland/electron-builder/issues/2807#event-1583076851 to everyone's attention—a conversation I started with the Electron-Builder community regarding @etpinard's concern.

Given a quick glance at the commit referenced, it appears that if we upgrade to v20.9.2 and do nothing else, the unwanted log message will disappear.

So, dare I say, that the problem seems pretty much solved?


James

**Comment by etpinard** [comment]
Awesome! Thanks @JamesCropcho for reaching out to them!

Before calling this fixed, would you mind running `npm update electron-builder --save-dev` and making a PR with package.json and package-lock.json updates?

**Comment by JamesCropcho** [comment]
Happily, @etpinard. I have done so: https://github.com/plotly/image-exporter/pull/80.
